name: CI-dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/superhow/projectX
          azure-pipeline-name: 'sahara-front-dev'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}